version: "2"
services:
  odoo:
    image: odoo:12
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - 5051:5051
    links:
      - db
    volumes:
      - ./pgadmin:/pgadmin
volumes:
  odoo-web-data:
  odoo-db-data:
